gitstuff

diff --git a/.github/workflows/merge-1-prod-to-rc.yml b/.github/workflows/merge-1-prod-to-rc.yml
--- a/.github/workflows/merge-1-prod-to-rc.yml
+++ b/.github/workflows/merge-1-prod-to-rc.yml
@@ -44,26 +44,28 @@ jobs:
         run: |
           git fetch origin
           if [[ "${{ env.latest_major_rc }}" == "" ]]; then
-            echo "No release candidate branch at all (never or only for the very first time). Exiting"
+            echo "No release candidate branch at all (never or only for the very first time). Aborting"
             exit 0
           elif git merge-base --is-ancestor "origin/${{ env.latest_major_rc }}" "origin/${{ env.source_branch }}"; then
-            echo "The latest major release candidate is merged into the current branch (meaning no active major release candidate). Exiting."
+            echo "The latest major release candidate is merged into the current branch (meaning no active major release candidate). Aborting."
             exit 0
           else
             target_branch=${{ env.latest_major_rc }}
           fi
           echo "target_branch=${target_branch}" >> $GITHUB_ENV
-          merge_base=$(git merge-base ${{ env.pr_source_branch }} origin/${{env.source_branch}})
-          if git log ${merge_base}..${{ env.pr_source_branch }} --oneline --decorate=full | grep -E '([0-9]+\.[0-9]+(\.[0-9]+)?)'; then
-            echo "Correct tag found."
-            if ! git diff --merge-base --quiet origin/${target_branch}; then
-              echo "to_be_merged=true" >> $GITHUB_ENV
-            else
-              echo "No difference found. Exiting"
-              exit 0
-            fi
+          latest_tag=$(git tag --sort=-committerdate | head -n1)
+          if [[ -z "$latest_tag" ]]; then
+            echo "No tag found in the pull request. Aborting."
+            exit 0
+          fi
+          if [[ ! "$latest_tag" =~ ^[0-9]+\.[0-9]+(\.[0-9]+)?$ ]]; then
+            echo "Invalid tag format: $latest_tag. Aborting."
+            exit 0
+          fi
+          if ! git diff --merge-base --quiet origin/${target_branch}; then
+            echo "to_be_merged=true" >> $GITHUB_ENV
           else
-            echo "No tag with the correct format. Exiting"
+            echo "No difference found. Aborting"
             exit 0
           fi
       - name: Get commit date of the source branch
